import os
import xml.etree.ElementTree as ET

from translators.translator_functions import write_results


def retrieve_results(filepath):
    """
    Retrieve analysis results from the n42 files generated by the Kromek D5 instrument
    :param filepath:
    :return:
    """
    it = ET.parse(filepath)
    root = it.getroot()

    ns = '{http://physics.nist.gov/N42/2011/N42}'

    resultsArray = []

    results = root.find(f'.//{ns}NuclideAnalysisResults')
    if results:
        results_elements = results.findall(f'{ns}Nuclide')
        for element in results_elements:
            nuclideID = element.find(f'{ns}NuclideName')
            confidenceValue = element.find(f'{ns}NuclideIDConfidenceValue')
            resultsArray.append((nuclideID.text, confidenceValue.text))

    return resultsArray


def main(input_dir, output_dir):
    in_files = [f for f in os.listdir(input_dir) if f.lower().endswith(".n42")]

    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    for fname in in_files:
        ResultsArray = retrieve_results(os.path.join(input_dir, fname))
        write_results(ResultsArray, os.path.join(output_dir, fname))
    return


if __name__ == "__main__":

    import sys

    if len(sys.argv) < 3:
        print("ERROR: Need input and output folder!")
        sys.exit(1)
    
    main(sys.argv[1], sys.argv[2])
