###############################################################################
# Copyright (c) 2018-2026 Lawrence Livermore National Security, LLC.
# Produced at the Lawrence Livermore National Laboratory
#
# Written by J. Brodsky, J. Chavez, S. Czyz, G. Kosinovsky, V. Mozin,
#            S. Sangiorgio.
#
# RASE-support@llnl.gov.
#
# LLNL-CODE-2014600, LLNL-CODE-829509
#
# All rights reserved.
#
# This file is part of RASE.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is furnished to do
# so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED,INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
###############################################################################
import shutil
from pathlib import Path

import pytest
import requests
from lxml import etree

from src.webid_utils import get_ids_from_webid


def test_get_ids_from_webid_live(tmp_path):
    """
    Integration test: call live WebID API on a sample .n42 file and verify .res output.
    """
    base_url = "https://full-spectrum.sandia.gov"
    # skip if WebID server not reachable
    try:
        requests.head(f"{base_url}/api/v1/info", timeout=5)
    except requests.RequestException:
        pytest.skip("WebID server not reachable")

    # Prepare input with provided sample file
    sample_src = Path(__file__).parent / "data" / "VGeneric_MNaI2x2_Co60.n42"
    assert sample_src.exists(), f"Sample file not found: {sample_src}"
    input_dir = tmp_path / "input"
    input_dir.mkdir()
    sample_dst = input_dir / sample_src.name
    shutil.copy(sample_src, sample_dst)

    # Prepare output directory
    output_dir = tmp_path / "output"
    output_dir.mkdir()

    # Invoke the utility with known DRF and synthesize background enabled
    get_ids_from_webid(
        str(input_dir),
        str(output_dir),
        drf="1x1/NaI Front",
        url=base_url,
        synthesize_bkg=True
    )

    # Verify .res files were created
    res_files = list(output_dir.glob("*.res"))
    assert res_files, "No .res files generated by get_ids_from_webid"

    # Check output is valid XML with a Co60 identification
    # Expect at least one <Identification><IDName>Co60</IDName></Identification>
    res_file = res_files[0]
    tree = etree.parse(str(res_file))
    root = tree.getroot()
    assert root.tag == "IdentificationResults"
    names = [elem.findtext('IDName') for elem in root.findall('Identification')]
    assert 'Co60' in names, f"Co60 not found in identifications: {names}"
